
def forca(x=0, j='null'):   # função que imprime a forca

    if x==0:
        print('')
        print('')
        print(f'Jogador: {j}')
        print('')
        print("------------")
        print("|  \033[33m|\033[m")
        print("| ")
        print("| ")
        print("| ")
        print("| ")
        print("| ")
        print("|")
    elif x==1:
        print('')
        print('')
        print(f'Jogador: {j}')
        print('')
        print("------------")
        print("|  \033[33m|\033[m")
        print("|  \033[33m0\033[m")
        print("| ")
        print("| ")
        print("| ")
        print("| ")
        print("|")
    elif x==2:
        print('')
        print('')
        print(f'Jogador: {j}')
        print('')
        print("------------")
        print("|  \033[33m|\033[m")
        print("|  \033[33m0\033[m")
        print("|  \033[33m|\033[m")
        print("| ")
        print("| ")
        print("| ")
        print("|")
    elif x==3:
        print('')
        print('')
        print(f'Jogador: {j}')
        print('')
        print("------------")
        print("|  \033[33m|\033[m")
        print("|  \033[33m0\033[m")
        print("| \033[33m-|\033[m")
        print("| ")
        print("| ")
        print("| ")
        print("|")
    elif x==4:
        print('')
        print('')
        print(f'Jogador: {j}')
        print('')
        print("------------ ")
        print("|  \033[33m|\033[m ")
        print("|  \033[33m0\033[m ")
        print("| \033[33m-|-\033[m ")
        print("| ")
        print("| ")
        print("| ")
        print("|")
    elif x==5:
        print('')
        print('')
        print(f'Jogador: {j}')
        print('')
        print("------------ ")
        print("|  \033[33m|\033[m ")
        print("|  \033[33m0\033[m ")
        print("| \033[33m-|-\033[m ")
        print("| \033[33m/\033[m ")
        print("| ")
        print("| ")
        print("|")
    elif x==6:
        print('')
        print('')
        print(f'Jogador: {j}')
        print('')
        print("------------ ")
        print("\033[31m|  |")
        print("|  0")
        print("| -|-")
        print("| / \ ")
        print("| ")
        print("| ")
        print("| \033[m")
        

